version: "3.8"

name: box

services:
  database:
    container_name: database
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "cQ3Hc1Wcr4"
      ACCEPT_EULA: "Y"
    volumes:
      - ./database/data:/var/opt/mssql/data
      - ./database/logs:/var/opt/mssql/log
      - ./database/backups:/var/opt/mssql/backup
    networks:
      - box-network

  api:
    container_name: api
    build:
      context: .
      dockerfile: ./box.api/Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - database
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - X-API-KEY=1234567890
      - ConnStr=Server=database;Database=box;User=sa;Password=cQ3Hc1Wcr4;TrustServerCertificate=True;
    volumes:
      - ./files:/box/
    networks:
      - box-network

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:latest
    container_name: fluent-bit
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - box-network

  promtail:
    image: grafana/promtail:2.6.1
    volumes:
      # custom config will read logs from the containers of
      # this project
      - ./loki/promtail-config.yml:/etc/promtail/config.yml

  loki:
    image: grafana/loki:latest
    container_name: loki
    networks:
      - box-network
    depends_on:
      - fluent-bit
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3900:3000"
    volumes:
      # directory must be created first, with uid:gid 472:472
      - ./volumes/grafana:/var/lib/grafana
      # automatically configure the loki datasource
      - ./loki/grafana/provisioning/:/etc/grafana/provisioning/
    depends_on:
      - loki
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
    networks:
      - box-network

networks:
  box-network:
    name: box-network
