# To renew the certificate, run the following command:
# docker compose run --rm certbot renew

version: "3.9"

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    platform: linux/amd64
    environment:
      SA_PASSWORD: ${DATABASE_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql/
    networks:
      - nginx-network

  nginx:
    image: nginx:stable-alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - api
    networks:
      - nginx-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - nginx-network

  api:
    image: ghcr.io/samymokhtari/box:latest
    restart: always
    env_file:
      - api-variables.env
    expose:
      - "5000"
    volumes:
      - box-data:/box/
    depends_on:
      - database
    networks:
      - nginx-network

  fluent-bit:
    image: grafana/fluent-bit-plugin-loki:latest
    restart: always
    container_name: fluent-bit
    environment:
      - LOKI_URL=http://loki:3100/loki/api/v1/push
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - nginx-network
    user: "472"

  promtail:
    image: grafana/promtail:2.6.1
    restart: always
    volumes:
      # custom config will read logs from the containers of
      # this project
      - ./loki/promtail-config.yml:/etc/promtail/config.yml
    user: "472"

  loki:
    image: grafana/loki:latest
    restart: always
    container_name: loki
    networks:
      - nginx-network
    depends_on:
      - fluent-bit

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    user: "1000"
    volumes:
      # directory must be created first, with uid:gid 472:472
      - ./volumes/grafana:/var/lib/grafana
      # automatically configure the loki datasource
      - ./loki/grafana/provisioning/:/etc/grafana/provisioning/
      - ./loki/grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - loki
    environment:
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    networks:
      - nginx-network

volumes:
  mssql-data:
    driver: local
  box-data:
    driver: local

networks:
  nginx-network:
    driver: bridge
