version: "3.9"

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql/
    networks:
      - nginx-network

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api
    networks:
      - nginx-network

  api:
    image: ${CONTAINER_REGISTRY}/box:latest
    environment:
      - ConnStr="Server=database,1433;Database=box;User ID=sa;Password=Password123;TrustServerCertificate=True;"
    expose:
      - "5000"
    volumes:
      - box-data:/box/
    depends_on:
      - database
    networks:
      - nginx-network

volumes:
  mssql-data:
    driver: local
  box-data:
    driver: local

networks:
  nginx-network:
    driver: bridge
