# To renew the certificate, run the following command:
# docker compose run --rm certbot renew

version: "3.9"

services:
  database:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: ${DATABASE_PASSWORD}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql/
    networks:
      - nginx-network

  nginx:
    image: nginx:stable-alpine
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - api
    networks:
      - nginx-network

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    networks:
      - nginx-network

  api:
    image: ghcr.io/samymokhtari/box:latest
    env_file:
      - api-variables.env
    expose:
      - "5000"
    volumes:
      - box-data:/box/
    depends_on:
      - database
    networks:
      - nginx-network

volumes:
  mssql-data:
    driver: local
  box-data:
    driver: local

networks:
  nginx-network:
    driver: bridge
