name: cd-api

on:
  push:
    branches: [main]

# permissions to write, build and push the docker image
permissions:
  contents: read
  packages: write
  deployments: write

jobs:
  build_push:
    runs-on: ubuntu-latest
    name: 'Docker Deployement Cloud Run'
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: write
    defaults:
      run:
        shell: bash
    environment: production
    env:
      DOTNET_VERSION: "6.0.x"
      environment: production
      location: europe-west1
      GITHUB_SHA: ${{ github.sha }}
      service_name: box-api
      app_name: box
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'
      - name: Configure docker
        run: |
          gcloud auth configure-docker ${{ env.location }}-docker.pkg.dev

      - name: Build the box api Docker image
        run: |
          docker build -f box.api/Dockerfile --tag ghcr.io/samymokhtari/box.api:${{ env.GITHUB_SHA }} .
          docker push ghcr.io/samymokhtari/box.api:${{ env.GITHUB_SHA }}

      - name: 'Deploy Cloud Run'
        run: |
          gcloud run deploy ${{ env.service_name }} \
          --image ghcr.io/samymokhtari/box.api:${{ env.GITHUB_SHA }} \
          --platform managed \
          --region ${{ env.location }} \
          --allow-unauthenticated \
          --cpu 1 \
          --max-instances 3 \
          --memory 512M \
          --no-use-http2 \
          --set-env-vars API_KEY=${{ secrets.API_KEY }} \
          --set-env-vars ConnStr=${{ secrets.CONN_STR }}
