name: cd-api

on:
  push:
    branches: [main, fix/cd]

# permissions to write, build and push the docker image
permissions:
  contents: read
  packages: write
  deployments: write

env:
  FULLPATH: /home/${{ secrets.SSH_USERNAME }}/scripts

jobs:
  build_push:
    runs-on: ubuntu-latest
    name: 'Docker Deployement Cloud Run'
    permissions:
      contents: 'read'
      id-token: 'write'
      packages: write
    defaults:
      run:
        shell: bash
    environment: production
    env:
      DOTNET_VERSION: "6.0.x"
      environment: production
      location: europe-west1
      GITHUB_SHA: ${{ github.sha }}
      service_name: box-api
      app_name: box
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
     
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set output version
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      
      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}

      - name: Build & Push docker image to Docker Hub
        run: |
          docker build -f box.api/Dockerfile --tag samy266/box:${{ steps.vars.outputs.sha_short }} --tag samy266/box:latest .
          docker push samy266/box:${{ steps.vars.outputs.sha_short }}
          docker push samy266/box:latest

      - name: 'Sync Server'
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo Starting Docker Compose...
            cd ${{ env.FULLPATH }} && sudo docker compose up -d
