name: ci-api

on:
  pull_request:
    branches: [main, develop]

jobs:
  ci:
    name: ci-${{matrix.os}}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: ["6.0.x"]
    steps:
      # Checks out the source code at the latest commit
      - uses: actions/checkout@v3
      # Installs the .NET SDK on the build machine
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet }}

      # Installs any NuGet packages required.
      - name: Install dependencies
        run: dotnet restore
      # Builds the project
      - name: Build
        run: dotnet build --configuration Release --no-restore /p:NetCoreBuild=true
      # Runs any tests in the project
      - name: Test
        run: dotnet test --verbosity normal /p:NetCoreBuild=true
